name: Production Deploy
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  workflow_call:
    inputs:
      build_id:
        required: true
        type: number
      deploy_target:
        required: true
        type: string
      perform_deploy:
        required: true
        type: boolean
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: debian-latest
    environment: Production
    if: ${{ inputs.perform_deploy }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy WC Theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
        run: deploy --build ${{ inputs.build_id }} --target ${{ inputs.deploy_target }}
