name: Production Deploy
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: debian-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - name: Deploy WC Theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
